"""
deckboss-fab — CAD/CAM equipment for deckboss git-agents

Equipment that lets git-agents generate, modify, and validate
CAD drawings and CAM instructions for physical hardware.

Dependencies (user-installed):
  - OpenSCAD:  sudo apt install openscad
  - FreeCAD:   sudo apt install freecad
  - Blender:   sudo apt install blender
  - Gazebo:    sudo apt install gazebo
  - PrusaSlicer/Cura: for G-code from STL

Git-agent usage:
  A git-agent receives a hardware spec (dimensions, mounting holes, ports)
  and generates OpenSCAD source files that produce STLs for 3D printing
  or DXFs for CNC cutting.
"""

import subprocess
import os
import json
import re


class CADGenerator:
    """Generate parametric CAD models from hardware specs."""

    def __init__(self, engine="openscad"):
        self.engine = engine

    def is_available(self) -> bool:
        return self._check_engine()

    def _check_engine(self) -> bool:
        try:
            r = subprocess.run([self.engine, "--version"],
                capture_output=True, text=True, timeout=5)
            return r.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def generate_jetson_case(self, spec: dict) -> str:
        """Generate an OpenSCAD script for a Jetson carrier case.

        spec keys:
          board: "orin-nano" | "orin-nx" | "nano"
          mounting: "standoff" | "rail" | "snap-fit"
          ports: list of "usb-c", "ethernet", "hdmi", "gpio", "csi"
          fan: bool
          dimensions: {width, height, depth} or auto from board
        """
        board = spec.get("board", "orin-nano")
        mounting = spec.get("mounting", "standoff")
        ports = spec.get("ports", ["usb-c", "ethernet", "hdmi", "gpio"])
        has_fan = spec.get("fan", False)

        # Board dimensions (mm)
        boards = {
            "orin-nano": {"w": 100, "h": 69, "standoff": 3.5, "thickness": 1.2},
            "orin-nx":   {"w": 100, "h": 69, "standoff": 3.5, "thickness": 1.2},
            "nano":      {"w": 100, "h": 45, "standoff": 2.5, "thickness": 1.0},
        }
        b = boards.get(board, boards["orin-nano"])
        dims = spec.get("dimensions", {})
        w = dims.get("width", b["w"] + 20)
        h = dims.get("height", b["h"] + 20)
        d = dims.get("depth", 30)

        # Port cutout dimensions
        port_cutouts = {
            "usb-c":    {"x": -1, "w": 10, "h": 4},
            "ethernet": {"x": -1, "w": 16, "h": 14},
            "hdmi":     {"x": -1, "w": 16, "h": 6},
            "gpio":     {"x": -1, "w": 52, "h": 6},
            "csi":      {"x": -1, "w": 24, "h": 4},
        }

        port_modules = ""
        port_y = 10
        for p in ports:
            c = port_cutouts.get(p, {"x": -1, "w": 10, "h": 4})
            port_modules += f"""
    // {p} cutout
    translate([0, {port_y}, {d/2 - 8}])
        cube([{c["w"]}, {c["h"]}, 10], center=true);
"""
            port_y += c["h"] + 4

        fan_module = ""
        if has_fan:
            fan_module = f"""
    // Fan cutout (40mm)
    translate([0, 0, {d/2}])
        cylinder(d=38, h=5, center=true, $fn=64);
    // Fan mounting holes
    for(angle = [45, 135, 225, 315])
        rotate([0, 0, angle])
            translate([16, 0, {d/2}])
                cylinder(d=3, h=6, center=true, $fn=16);
"""

        standoff_module = ""
        if mounting == "standoff":
            so = b["standoff"]
            so_r = round(so / 2 + 0.3, 1)
            mg = 5
            x1 = round(-w/2 + mg + so, 1)
            x2 = round(w/2 - mg - so, 1)
            y1 = round(-h/2 + mg + so, 1)
            y2 = round(h/2 - mg - so, 1)
            standoff_module = ""
            standoff_module += f"    // Standoff holes ({so}mm M3)\n"
            standoff_module += f"    standoff_r = {so_r};\n"
            standoff_module += f"    positions = [[{x1}, {y1}], [{x2}, {y1}], [{x1}, {y2}], [{x2}, {y2}]];\n"
            standoff_module += "    for(pos = positions)\n"
            standoff_module += "        translate([pos[0], pos[1], 0])\n"
            standoff_module += "            cylinder(r=standoff_r, h=6, center=true, $fn=16);\n"

        scad = f"""// Jetson {board} case — generated by deckboss-fab
// Board: {board} ({b["w"]}x{b["h"]}mm)
// Case:  {w}x{h}x{d}mm
// Mounting: {mounting}
// Ports: {", ".join(ports)}
// Fan: {has_fan}

$fn = 32;
wall = 2;

difference() {{
    // Main case body
    minkowski() {{
        cube([{w - 4}, {h - 4}, {d - 4}], center=true);
        sphere(r=wall);
    }}

    // Interior cavity
    translate([0, 0, 1])
        cube([{w - 6}, {h - 6}, {d - 2}], center=true);

    // Bottom opening (for connectors)
    translate([0, 0, -{d/2 + 1}])
        cube([{w/2}, {h - 10}, 6], center=true);

    // Board standoff holes
{standoff_module}
    // Port cutouts
{port_modules}
    // Fan
{fan_module}
}}

// Lid (uncomment to export separately)
// translate([0, 0, {d/2 + 2}])
//     difference() {{
//         minkowski() {{
//             cube([{w - 4}, {h - 4}, 3], center=true);
//             sphere(r=wall);
//         }}
//         cube([{w - 8}, {h - 8}, 4], center=true);
//     }}
"""
        return scad

    def render_stl(self, scad_path: str, output_path: str = None) -> str:
        """Render OpenSCAD to STL."""
        if output_path is None:
            output_path = scad_path.replace(".scad", ".stl")
        r = subprocess.run(
            ["openscad", "-o", output_path, scad_path],
            capture_output=True, text=True, timeout=120)
        if r.returncode == 0:
            return output_path
        raise RuntimeError(f"OpenSCAD failed: {r.stderr}")

    def render_dxf(self, scad_path: str, output_path: str = None) -> str:
        """Render OpenSCAD projection to DXF (for laser/CNC)."""
        if output_path is None:
            output_path = scad_path.replace(".scad", ".dxf")
        # Add projection at top of file temporarily
        r = subprocess.run(
            ["openscad", "-o", output_path, "-D", "projection=true",
             scad_path],
            capture_output=True, text=True, timeout=120)
        if r.returncode == 0:
            return output_path
        raise RuntimeError(f"OpenSCAD DXF failed: {r.stderr}")


class GCodeGenerator:
    """Generate G-code from STL using slicer CLI."""

    def __init__(self, slicer="prusaslicer"):
        self.slicer = slicer

    def is_available(self) -> bool:
        try:
            r = subprocess.run([self.slicer, "--help"],
                capture_output=True, text=True, timeout=5)
            return r.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def slice(self, stl_path: str, config: dict = None) -> str:
        """Slice STL to G-code."""
        if config is None:
            config = {
                "layer_height": 0.2,
                "infill": 20,
                "walls": 2,
                "support": "on",
            }

        output = stl_path.replace(".stl", ".gcode")
        cmd = [
            self.slicer,
            "-o", output,
            f"--layer-height", str(config.get("layer_height", 0.2)),
            f"--infill", str(config.get("infill", 20)),
            f"--perimeters", str(config.get("walls", 2)),
        ]
        if config.get("support"):
            cmd.extend(["--support", "on"])

        cmd.append(stl_path)
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if r.returncode == 0:
            return output
        raise RuntimeError(f"Slicer failed: {r.stderr}")


class SimulationRunner:
    """Run physics simulations for robot prototyping."""

    def __init__(self, engine="gazebo"):
        self.engine = engine

    def is_available(self) -> bool:
        try:
            r = subprocess.run([self.engine, "--version"],
                capture_output=True, text=True, timeout=5)
            return r.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def list_available(self) -> dict:
        """Check which simulation tools are installed."""
        tools = {}
        for name, cmd in [
            ("gazebo", "gazebo"),
            ("mujoco", "simulate"),
            ("blender", "blender"),
            ("freecad", "freecad"),
            ("openscad", "openscad"),
            ("prusaslicer", "prusaslicer"),
            ("cura", "cura"),
            ("inkscape", "inkscape"),
            ("kicad", "kicad"),
            ("arduino-cli", "arduino-cli"),
        ]:
            try:
                r = subprocess.run([cmd, "--version"],
                    capture_output=True, text=True, timeout=5)
                tools[name] = r.returncode == 0
            except (FileNotFoundError, subprocess.TimeoutExpired):
                tools[name] = False
        return tools


class HardwareSpecParser:
    """Parse hardware requirements from natural language or structured specs."""

    BOARD_SPECS = {
        "jetson-orin-nano": {
            "board": "orin-nano", "soc": "Orin Nano",
            "size": [100, 69, "21.7"], "usb": "USB-C 3.2 + USB-A",
            "ethernet": "1x GbE", "hdmi": "2x HDMI 2.1",
            "gpio": "40-pin", "csi": "2x MIPI CSI-2",
            "power": "9-20V DC", "weight": "~70g",
        },
        "jetson-orin-nx": {
            "board": "orin-nx", "soc": "Orin NX",
            "size": [100, 69, "26"], "usb": "USB-C 3.2 + USB-A",
            "ethernet": "1x 10GbE", "hdmi": "2x HDMI 2.1",
            "gpio": "40-pin", "csi": "2x MIPI CSI-2",
            "power": "9-20V DC", "weight": "~100g",
        },
        "raspberry-pi-5": {
            "board": "rpi5", "soc": "BCM2712",
            "size": [85, 56, "16.8"], "usb": "2x USB 3.0 + 2x USB 2.0",
            "ethernet": "1x GbE", "hdmi": "2x micro-HDMI",
            "gpio": "40-pin", "csi": "2x MIPI CSI",
            "power": "5V/5A USB-C", "weight": "~46g",
        },
    }

    def parse(self, spec: str) -> dict:
        """Parse a hardware spec string into a structured dict."""
        spec_lower = spec.lower()
        board = "orin-nano"

        for key in self.BOARD_SPECS:
            if key.replace("-", " ") in spec_lower or key in spec_lower:
                board = key.split("-")[-1] if "jetson" in key else key
                break
        if "pi" in spec_lower or "raspberry" in spec_lower:
            board = "rpi5"

        return {
            "board": board,
            "mounting": "standoff" if "standoff" in spec_lower else "snap-fit",
            "ports": [p for p in ["usb-c", "ethernet", "hdmi", "gpio", "csi"]
                      if p in spec_lower],
            "fan": "fan" in spec_lower or "cooling" in spec_lower,
        }

    def get_board_info(self, board: str) -> dict:
        for key, val in self.BOARD_SPECS.items():
            if board in key or key.endswith(board):
                return val
        return self.BOARD_SPECS["jetson-orin-nano"]
